// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// BDtrans_numeric
Rcpp::RObject BDtrans_numeric(const Rcpp::RObject& x);
RcppExport SEXP _BigDataStatMeth_BDtrans_numeric(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::RObject& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(BDtrans_numeric(x));
    return rcpp_result_gen;
END_RCPP
}
// BDtrans_hdf5
Rcpp::RObject BDtrans_hdf5(const Rcpp::RObject& x);
RcppExport SEXP _BigDataStatMeth_BDtrans_hdf5(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::RObject& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(BDtrans_hdf5(x));
    return rcpp_result_gen;
END_RCPP
}
// timesTwo
NumericVector timesTwo(NumericVector x);
RcppExport SEXP _BigDataStatMeth_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BigDataStatMeth_BDtrans_numeric", (DL_FUNC) &_BigDataStatMeth_BDtrans_numeric, 1},
    {"_BigDataStatMeth_BDtrans_hdf5", (DL_FUNC) &_BigDataStatMeth_BDtrans_hdf5, 1},
    {"_BigDataStatMeth_timesTwo", (DL_FUNC) &_BigDataStatMeth_timesTwo, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_BigDataStatMeth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
