# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Remove SNPs in hdf5 omic dataset with low data
#'
#' Remove SNPs in hdf5 omic dataset with low data
#' 
#' @param filename, character array indicating the name of the file to create
#' @param group, character array indicating the input group where the data set to be imputed is. 
#' @param dataset, character array indicating the input dataset to be imputed
#' @param outgroup, character array indicating group where the data set will be saved after remove data with if `outgroup` is NULL, output dataset is stored in the same input group. 
#' @param outdataset, character array indicating dataset to store the resulting data after imputation if `outdataset` is NULL, input dataset will be overwritten. 
#' @param pcent, by default pcent = 0.5. Numeric indicating the percentage to be considered to remove SNPs, SNPS with percentage equal or higest will be removed from data
#' @param SNPincols, boolean by default = true, if true, indicates that SNPs are in cols, if SNPincols = false indicates that SNPs are in rows.
#' @return Original hdf5 data file with imputed data
#' @export
bdRemovelowdata <- function(filename, group, dataset, outgroup, outdataset, pcent, SNPincols) {
    .Call('_BigDataStatMeth_bdRemovelowdata', PACKAGE = 'BigDataStatMeth', filename, group, dataset, outgroup, outdataset, pcent, SNPincols)
}

#' Impute SNPs in hdf5 omic dataset 
#'
#' Impute SNPs in hdf5 omic dataset 
#' 
#' @param filename, character array indicating the name of the file to create
#' @param group, character array indicating the input group where the data set to be imputed is. 
#' @param dataset, character array indicating the input dataset to be imputed
#' @param bycols, boolean by default = true, true indicates that the imputation will be done by columns, otherwise, the imputation will be done by rows
#' @param outgroup, optional character array indicating group where the data set will be saved after imputation if `outgroup` is NULL, output dataset is stored in the same input group. 
#' @param outdataset, optional character array indicating dataset to store the resulting data after imputation if `outdataset` is NULL, input dataset will be overwritten. 
#' @return Original hdf5 data file with imputed data
#' @export
bdImputeSNPHDF5 <- function(filename, group, dataset, outgroup, outdataset, bycols) {
    .Call('_BigDataStatMeth_bdImputeSNPHDF5', PACKAGE = 'BigDataStatMeth', filename, group, dataset, outgroup, outdataset, bycols)
}

#' Normalize dataset in hdf5 file
#' 
#' This function normalize data scaling, centering or scaling and centering in a dataset stored in hdf5 file
#' 
#' @param filename string file name where dataset to normalize is stored
#' @param group string or Delayed Array Matrix
#' @param dataset string or Delayed Array Matrix
#' @param bcenter logical (default = TRUE) if TRUE, centering is done by subtracting the column means
#' @param bscale logical (default = TRUE) if TRUE, centering is done by subtracting the column means
#' @param wsize integer (default = 1000), file block size to read to perform normalization
#' @return file with scaled, centered or scaled and centered dataset
#' @examples
#' 
#' @export
Normalize_hdf5 <- function(filename, group, dataset, bcenter = NULL, bscale = NULL, wsize = NULL) {
    .Call('_BigDataStatMeth_Normalize_hdf5', PACKAGE = 'BigDataStatMeth', filename, group, dataset, bcenter, bscale, wsize)
}

#' PCA Descomposition
#' 
#' Compute PCA
#' 
#' @param filename string, file name where dataset is stored 
#' @param group string group name  where dataset is stored in file
#' @param dataset string dataset name with data to perform PCA
#' @return original file with results in folder PCA/<datasetname>
#' @export
bdPCA_hdf5 <- function(filename, group, dataset) {
    .Call('_BigDataStatMeth_bdPCA_hdf5', PACKAGE = 'BigDataStatMeth', filename, group, dataset)
}

#' LOOE
#' 
#' This function performs ...
#' 
#' @param X numerical or Delayed Array matrix
#' @param Y numerical or Delayed Array vector
#' @param paral (optional, default = true) if paral=true performs parallel computation.
#' @param nl ...
#' @param ml ...
#' @param l ...
#' @param threads (optional) only if bparal = true, number of concurrent threads in parallelization if threads is null then threads =  maximum number of threads available
#' @return coef ...
#' @return Ginv  ...
#' @return lambda.min  ...
#' @return lambdas  ...
#' @return looe ...
#' @examples
#' n <- 500
#' p <- 200
#' M <- matrix(rnorm(n*p), nrow=n, ncol=p)
#' Y <- 2.4*M[,1] + 1.6*M[,2] - 0.4*M[,5]
#' 
#' MD <- DelayedArray(M)
#' YD <- DelayedArray(as.matrix(Y))
#' 
#' looe <- LOOE(M,Y,paral=TRUE),
#' looe_delayed <- LOOE(MD,YD,paral=TRUE)
#' 
#' looe$lambda.min
#' looe$lambdas
#' looe_delayed$coef[1:10]
#' @export
LOOE <- function(X, Y, paral, nl = NULL, ml = NULL, l = NULL, threads = NULL) {
    .Call('_BigDataStatMeth_LOOE', PACKAGE = 'BigDataStatMeth', X, Y, paral, nl, ml, l, threads)
}

#' Normalize Delayed Array matrix
#' 
#' This function performs a numerical or Delayed Array matrix normalization
#' 
#' @param X numerical or Delayed Array Matrix
#' @param bcenter logical (default = TRUE) if TRUE, centering is done by subtracting the column means
#' @param bscale logical (default = TRUE) if TRUE, centering is done by subtracting the column means
#' @return numerical matrix
#' @examples
#' m <- 500
#' n <- 100 
#' x <- matrix(rnorm(m*n), nrow=m, ncol=n)
#' 
#' # with numeric matrix
#' Normalize_Data(x)
#' 
#' # with Delaeyd Array
#' Dx <- DelayedArray(x)
#' 
#' # Center and scale
#' Normalize_Data(Dx)
#' 
#' # Only scale
#' Normalize_Data(Dx, bcenter = FALSE)
#' 
#' # Only center
#' Normalize_Data(Dx, bscale = FALSE)
#' 
#' @export
Normalize_Data <- function(x, bcenter = NULL, bscale = NULL) {
    .Call('_BigDataStatMeth_Normalize_Data', PACKAGE = 'BigDataStatMeth', x, bcenter, bscale)
}

#' Matrix - Weighted vector Multiplication with numerical or DelayedArray data
#' 
#' This function performs a weighted product of a matrix(X) with a weighted diagonal matrix (w)
#' 
#' @param X numerical or Delayed Array matrix
#' @param w vector with weights
#' @param op string indicating if operation  "Xw" , "wX" or "wXw"
#' @return numerical matrix 
#' @examples
#' n <- 100
#' p <- 60
#' 
#' X <- matrix(rnorm(n*p), nrow=n, ncol=p)
#' 
#' u <- runif(n)
#' w <- u * (1 - u)
#' 
#' # by columnes
#' bdwXw(X, w,"wX") 
#' 
#' # by rows
#' bdwXw(X, w,"Xw")
#' 
#' # by columns and rows
#' bdwXw(X, w,"wXw")
#' 
#' # with Delayed Array
#' 
#' DX <- DelayedArray(X)
#' dw <- DelayedArray(w)
#' 
#' bdwXw(DX, dw,"wX")
#' bdwXw(DX, dw,"Xw")
#' 
#' @export
bdwXw <- function(X, W, op) {
    .Call('_BigDataStatMeth_bdwXw', PACKAGE = 'BigDataStatMeth', X, W, op)
}

#' Crossproduct and transposed crossproduct of DelayedArray
#' 
#' This function performs a crossproduct or transposed crossproduct of numerical or DelayedArray matrix.
#' 
#' @param X numerical or Delayed Array matrix
#' @param transposed (optional, default = false) boolean indicating if we have to perform a crossproduct (transposed=false) or transposed crossproduct (transposed = true)
#' @return numerical matrix with crossproduct or transposed crossproduct 
#' @examples
#' n <- 100
#' p <- 60
#' 
#' X <- matrix(rnorm(n*p), nrow=n, ncol=p)
#' 
#' # without DelayedArray
#' bdcrossprod(X)
#' bdcrossprod(X, transposed = TRUE)
#' 
#' # with DelayedArray
#' XD <- DelayedArray(X)
#' bdcrossprod(XD)
#' bdcrossprod(XD, transpoded = TRUE)
#' 
#' @export
bdcrossprod <- function(a, transposed = NULL) {
    .Call('_BigDataStatMeth_bdcrossprod', PACKAGE = 'BigDataStatMeth', a, transposed)
}

#' Matrix - Weighted vector Multiplication with numerical or DelayedArray data
#' 
#' This function performs a weighted product of a matrix(X) with a weighted diagonal matrix (w)
#' 
#' @param X numerical or Delayed Array matrix
#' @param w vector with weights
#' @param op string indicating if operation 'xtwx' and 'xwxt' for weighted cross product (Matrix - Vector - Matrix) or 'Xw' and 'wX' for weighted product (Matrix - Vector)
#' @return numerical matrix 
#' @examples
#' n <- 100
#' p <- 60
#' 
#' X <- matrix(rnorm(n*p), nrow=n, ncol=p)
#' 
#' u <- runif(n)
#' w <- u * (1 - u)
#' bdwproduct(X, w,"xtwx")
#' bdwproduct(X, w,"xwxt")
#' 
#' # with Delayed Array
#' 
#' DX <- DelayedArray(X)
#' dw <- DelayedArray(w)
#' 
#' bdwproduct(DX, dw,"xtwx")
#' bdwproduct(DX, dw,"xwxt")
#' 
#' @export
bdwproduct <- function(a, w, op) {
    .Call('_BigDataStatMeth_bdwproduct', PACKAGE = 'BigDataStatMeth', a, w, op)
}

#' Matrix - Weighted Scalar Multiplication with numerical or DelayedArray data
#' 
#' This function performs a weighted product of a matrix(X) with a weighted diagonal matrix (w)
#' 
#' @param X numerical or Delayed Array matrix
#' @param w scalar, weight
#' @param op string indicating if operation  "Xw" or "wX"
#' @return numerical matrix 
#' @examples
#' n <- 100
#' p <- 60
#' 
#' X <- matrix(rnorm(n*p), nrow=n, ncol=p)
#' w <- 0.75
#' 
#' bdScalarwproduct(X, w,"Xw")
#' bdScalarwproduct(X, w,"Wx")
#' 
#' # with Delayed Array
#' 
#' DX <- DelayedArray(X)
#' 
#' bdScalarwproduct(DX, w,"Xw")
#' bdScalarwproduct(DX, w,"wX")
#' 
#' @export
bdScalarwproduct <- function(a, w, op) {
    .Call('_BigDataStatMeth_bdScalarwproduct', PACKAGE = 'BigDataStatMeth', a, w, op)
}

#' Block matrix multiplication with Delayed Array Object
#' 
#' This function performs a block matrix-matrix multiplication with numeric matrix or Delayed Arrays
#' 
#' @param a a double matrix.
#' @param b a double matrix.
#' @param block_size (optional, defalut = 128) block size to make matrix multiplication, if `block_size = 1` no block size is applied (size 1 = 1 element per block)
#' @param paral, (optional, default = TRUE) if paral = TRUE performs parallel computation else performs seria computation
#' @param threads (optional) only if bparal = true, number of concurrent threads in parallelization if threads is null then threads =  maximum number of threads available
#' @param bigmatrix (optiona, default = 5000) maximum number of rows or columns to consider as big matrix and work with
#' hdf5 files, by default a matrix with more than 5000 rows or files is considered big matrix and computation is made in disk 
#' @param mixblock_size (optiona, default = 128), only if we are working with big matrix and parallel computation = true. 
#' Block size for mixed computation in big matrix parallel. Size of the block to be used to perform parallelized memory 
#' memory of the block read from the disk being processed.
#' @param outfile (optional) file name to work with hdf5 if we are working with big matrix in disk.
#' @return A List with : 
#' \itemize{
#'   \item{"matrix"}{ Result matrix if execution has been performed in memory}
#'   \item{"filename"}{ HDF5 filename if execution has been performed in disk, HDF5 file contains : 
#'     \itemize{
#'       \item{"INPUT"}{hdf5 group with input matrix A and B}
#'       \item{"OUTPUT"}{hdf5 group with output matrix C}
#'     }with input and output matrix.
#'   }
#' }
#' @examples
#' # with numeric matrix
#' m <- 500
#' k <- 1500
#' n <- 400
#' A <- matrix(rnorm(n*p), nrow=n, ncol=k)
#' B <- matrix(rnorm(n*p), nrow=k, ncol=n)
#' 
#' Bblockmult(A,B,128, TRUE)
#' 
#' # with Delaeyd Array
#' AD <- DelayedArray(A)
#' BD <- DelayedArray(B)
#' 
#' Bblockmult(AD,BD,128, TRUE)
#' @export
blockmult <- function(a, b, block_size = NULL, paral = NULL, threads = NULL, bigmatrix = NULL, outfile = NULL, mixblock_size = NULL) {
    .Call('_BigDataStatMeth_blockmult', PACKAGE = 'BigDataStatMeth', a, b, block_size, paral, threads, bigmatrix, outfile, mixblock_size)
}

CholFactor <- function(a) {
    .Call('_BigDataStatMeth_CholFactor', PACKAGE = 'BigDataStatMeth', a)
}

CholSolve <- function(a, b) {
    .Call('_BigDataStatMeth_CholSolve', PACKAGE = 'BigDataStatMeth', a, b)
}

inversechol_par <- function(a, threads = NULL) {
    .Call('_BigDataStatMeth_inversechol_par', PACKAGE = 'BigDataStatMeth', a, threads)
}

partCrossProd <- function(X) {
    .Call('_BigDataStatMeth_partCrossProd', PACKAGE = 'BigDataStatMeth', X)
}

partCrossProd_block <- function(X) {
    .Call('_BigDataStatMeth_partCrossProd_block', PACKAGE = 'BigDataStatMeth', X)
}

parCrossProd <- function(X) {
    .Call('_BigDataStatMeth_parCrossProd', PACKAGE = 'BigDataStatMeth', X)
}

parCrossProd_block <- function(X) {
    .Call('_BigDataStatMeth_parCrossProd_block', PACKAGE = 'BigDataStatMeth', X)
}

partCrossProdEigen <- function(X) {
    .Call('_BigDataStatMeth_partCrossProdEigen', PACKAGE = 'BigDataStatMeth', X)
}

#' Matrix multiplication with Delayed Array Object (RcppParallel)
#' 
#' This function performs a block matrix-matrix multiplication with numeric matrix or Delayed Arrays
#' 
#' @param a a double matrix.
#' @param b a double matrix.
#' @param op, (optional, default = "xy"), if op="xy" then performs the x\%*\%y matrix multiplication, if op = "xty" preforms t(X)\%*\% Y, if op = "xyt" performs X\%*\%t(Y)
#' @return numerical matrix
#' @examples
#' # with numeric matrix
#' m <- 500
#' k <- 300
#' n <- 400
#' A <- matrix(rnorm(n*p), nrow=n, ncol=k)
#' B <- matrix(rnorm(n*p), nrow=k, ncol=n)
#' 
#' parXYProd(A,B,128, TRUE)
#' 
#' # with Delaeyd Array
#' AD <- DelayedArray(A)
#' BD <- DelayedArray(B)
#' 
#' parXYProd(AD,BD,128, TRUE)
#' 
#' @export
parXYProd <- function(X, Y, op = NULL) {
    .Call('_BigDataStatMeth_parXYProd', PACKAGE = 'BigDataStatMeth', X, Y, op)
}

#' Block matrix multiplication with Delayed Array Object
#' 
#' This function performs a block matrix-matrix multiplication with numeric matrix or Delayed Arrays
#' 
#' @param a a double matrix.
#' @param b a double matrix.
#' @param op, (optional, default = "xy"), if op="xy" then performs the x\%*\%y matrix multiplication, if op = "xty" preforms t(X)\%*\% Y, if op = "xyt" performs X\%*\%t(Y)
#' @return numerical matrix
#' @examples
#' # with numeric matrix
#' m <- 500
#' k <- 1500
#' n <- 400
#' A <- matrix(rnorm(n*p), nrow=n, ncol=k)
#' B <- matrix(rnorm(n*p), nrow=k, ncol=n)
#' 
#' Bblockmult(A,B,128, TRUE)
#' 
#' # with Delaeyd Array
#' AD <- DelayedArray(A)
#' BD <- DelayedArray(B)
#' 
#' Bblockmult(AD,BD,128, TRUE)
#' 
#' @export
parXYProdBlock <- function(X, Y, op = NULL) {
    .Call('_BigDataStatMeth_parXYProdBlock', PACKAGE = 'BigDataStatMeth', X, Y, op)
}

parxwxt <- function(X, W) {
    .Call('_BigDataStatMeth_parxwxt', PACKAGE = 'BigDataStatMeth', X, W)
}

parxtwx <- function(X, W) {
    .Call('_BigDataStatMeth_parxtwx', PACKAGE = 'BigDataStatMeth', X, W)
}

parXy <- function(X, Y) {
    .Call('_BigDataStatMeth_parXy', PACKAGE = 'BigDataStatMeth', X, Y)
}

JacobianSVD <- function(X) {
    .Call('_BigDataStatMeth_JacobianSVD', PACKAGE = 'BigDataStatMeth', X)
}

bdtsvd <- function(X, k = NULL) {
    .Call('_BigDataStatMeth_bdtsvd', PACKAGE = 'BigDataStatMeth', X, k)
}

bdsvd <- function(X) {
    .Call('_BigDataStatMeth_bdsvd', PACKAGE = 'BigDataStatMeth', X)
}

#' Pseudo-Inverse
#' 
#' Compute the pseudo-inverse of a singular matrix
#' 
#' @param Singular matrix (m x n)
#' @return Pseudo-inverse matrix of A
#' @export
bdpseudoinv <- function(X) {
    .Call('_BigDataStatMeth_bdpseudoinv', PACKAGE = 'BigDataStatMeth', X)
}

#' QR Decomposition 
#' 
#' This function compute QR decomposition (also called a QR factorization) 
#' of a matrix \code{A} into a product \code{A = QR} of an 
#' orthogonal matrix Q and an upper triangular matrix R.
#' 
#' @param X a real square matrix 
#' @param boolean thin, if thin = true returns Q thin  decomposition else returns Q full decomposition, default thin = false
#' @return List with orthogonal matrix \code{Q}  and upper triangular matrix \code{R}
#' @export
bdQR <- function(X, thin = NULL) {
    .Call('_BigDataStatMeth_bdQR', PACKAGE = 'BigDataStatMeth', X, thin)
}

review_decomposition <- function(R, n) {
    .Call('_BigDataStatMeth_review_decomposition', PACKAGE = 'BigDataStatMeth', R, n)
}

#' Solves matrix equations : A*X = B
#' 
#' 
#' 
#' @param R numerical or Delayed Array matrix. 
#' @param Z numerical or Delayed Array matrix.
#' @return X numerical matrix. 
#' @examples
#' 
#' @export
bddtrsm <- function(R, Z, threads = NULL) {
    .Call('_BigDataStatMeth_bddtrsm', PACKAGE = 'BigDataStatMeth', R, Z, threads)
}

#' Create hdf5 data file and write data to it
#'
#' Creates a hdf5 file with numerical data matrix,
#' 
#' @param filename, character array indicating the name of the file to create
#' @param folder, character array indicating folder name to put the matrix in hdf5 file
#' @param mat numerical data matrix
#' @return none
#' @export
Create_HDF5_matrix_file <- function(filename, mat, group = NULL, dataset = NULL) {
    .Call('_BigDataStatMeth_Create_HDF5_matrix_file', PACKAGE = 'BigDataStatMeth', filename, mat, group, dataset)
}

#' Write matrix to existing hdf5 file
#'
#' Creates a hdf5 file with numerical data matrix,
#' 
#' @param filename, character array indicating the name of the file to create
#' @param mat numerical data matrix
#' @param folder, character array indicating folder name to put the matrix in hdf5 file
#' @param dataset, character array indicating the dataset name that contains the matix data
#' @return none
#' @export
Create_HDF5_matrix <- function(mat, filename, group, dataset) {
    .Call('_BigDataStatMeth_Create_HDF5_matrix', PACKAGE = 'BigDataStatMeth', mat, filename, group, dataset)
}

#' Remove element group or dataset from  hdf5 file
#'
#' Remove group or dataset from  hdf5 file
#' 
#' @param filename, character array indicating the name of the file to create
#' @param path to element, character array indicating the complete route to the element to be removed (folder or dataset). 
#' @return none
#' @export
Remove_HDF5_element <- function(filename, element) {
    .Call('_BigDataStatMeth_Remove_HDF5_element', PACKAGE = 'BigDataStatMeth', filename, element)
}

#' Inverse Cholesky of Delayed Array
#' 
#' This function get the inverse of a numerical or Delayed Array matrix. If x is hermitian and positive-definite matrix then 
#' performs get the inverse using Cholesky decomposition
#' 
#' 
#' @param x numerical or Delayed Array matrix. If x is Hermitian and positive-definite performs
#' @return inverse matrix of d 
#' @examples
#' 
#' A <- matrix(c(3,4,3,4,8,6,3,6,9), byrow = TRUE, ncol = 3)
#' bdInvCholesky(A)
#' 
#' # with Delayed Array
#' DA <- DelayedArray(A)
#' bdInvCholesky(DA)
#' 
#' @export
bdInvCholesky <- function(x) {
    .Call('_BigDataStatMeth_bdInvCholesky', PACKAGE = 'BigDataStatMeth', x)
}

#' SVD of DelayedArray 
#' 
#' This function performs a svd decomposition of numerical matrix or Delayed Array
#' 
#' @param x numerical or Delayed Array matrix
#' @param k number of eigen values , this should satisfy k = min(n, m) - 1
#' @param nev (optional, default nev = n-1) Number of eigenvalues requested. This should satisfy 1≤ nev ≤ n, where n is the size of matrix. 
#' @param bcenter (optional, defalut = TRUE) . If center is TRUE then centering is done by subtracting the column means (omitting NAs) of x from their corresponding columns, and if center is FALSE, no centering is done.
#' @param bscale (optional, defalut = TRUE) .  If scale is TRUE then scaling is done by dividing the (centered) columns of x by their standard deviations if center is TRUE, and the root mean square otherwise. If scale is FALSE, no scaling is done.
#' @return u eigenvectors of AA^t, mxn and column orthogonal matrix
#' @return v eigenvectors of A^tA, nxn orthogonal matrix
#' @return d singular values, nxn diagonal matrix (non-negative real values)
#' @examples
#' n <- 500
#' A <- matrix(rnorm(n*n), nrow=n, ncol=n)
#' AD <- DelayedArray(A)
#' 
#' # svd without normalization
#' bdSVD( A, bscale = FALSE, bcenter = FALSE ), # No matrix normalization
#' decsvd$d
#' decsvd$u
#' 
#' # svd with normalization
#' decvsd <- bdSVD( A, bscale = TRUE, bcenter = TRUE), # Matrix normalization
#' 
#' decsvd$d
#' decsvd$u
#' 
#' # svd with scaled matrix (sd)
#' decvsd <- bdSVD( A, bscale = TRUE, bcenter = FALSE), # Scaled matrix
#' 
#' decsvd$d
#' decsvd$u
#' # svd with centered matrix (sd)
#' decvsd <- bdSVD( A, bscale = FALSE, bcenter = TRUE), # Centered matrix
#' decsvd$d
#' decsvd$u
#' 
#' @export
bdSVD <- function(x, k = 0L, nev = 0L, bcenter = TRUE, bscale = TRUE) {
    .Call('_BigDataStatMeth_bdSVD', PACKAGE = 'BigDataStatMeth', x, k, nev, bcenter, bscale)
}

#' Block SVD decomposition using an incremental algorithm.
#'
#' Singular values and left singular vectors of a real nxp matrix 
#' @title Block SVD decomposition using an incremental algorithm.
#' @param x a real nxp matrix in hdf5 file
#' @param group group in hdf5 data file where dataset is located
#' @param dataset matrix dataset with data to perform SVD
#' @param k number of local SVDs to concatenate at each level 
#' @param q number of levels
#' @param bcenter (optional, defalut = TRUE) . If center is TRUE then centering is done by subtracting the column means (omitting NAs) of x from their corresponding columns, and if center is FALSE, no centering is done.
#' @param bscale (optional, defalut = TRUE) .  If scale is TRUE then scaling is done by dividing the (centered) columns of x by their standard deviations if center is TRUE, and the root mean square otherwise. If scale is FALSE, no scaling is done.
#' @param threads (optional) only used in some operations inside function. If threads is null then threads =  maximum number of threads available - 1.
#' @return a list of three components with the singular values and left and right singular vectors of the matrix
#' @return A List with : 
#' \itemize{
#'   \item{"u"}{ eigenvectors of AA^t, mxn and column orthogonal matrix }
#'   \item{"v"}{ eigenvectors of A^tA, nxn orthogonal matrix }
#'   \item{"v"}{ singular values, nxn diagonal matrix (non-negative real values) }
#' }
#' @export
bdSVD_hdf5 <- function(x, group = NULL, dataset = NULL, k = 2L, q = 1L, bcenter = TRUE, bscale = TRUE, threads = NULL) {
    .Call('_BigDataStatMeth_bdSVD_hdf5', PACKAGE = 'BigDataStatMeth', x, group, dataset, k, q, bcenter, bscale, threads)
}

#' @export
bdSVD_lapack <- function(X, bcenter = TRUE, bscale = TRUE) {
    .Call('_BigDataStatMeth_bdSVD_lapack', PACKAGE = 'BigDataStatMeth', X, bcenter, bscale)
}

